"""
knowledge/qdrant_client.py
─────────────────────────────────────────────────────────────────────────────
Symptom semantic search client.

QdrantClient loads its corpus from two sources in priority order:

  1. Neo4j (primary) — queries all Symptom nodes (category='symptom') at
     startup.  Requires Neo4j to be running and populated.

  2. symptom_index.json (fallback) — the JSON file produced by
     `neo4j-setup/2_parse_ontologies.py` (no database needed).
     Activated automatically when Neo4j is unreachable or empty.

Both sources build an identical in-process sentence-transformer index.
No separate Qdrant server is ever required.

Interface contract — both implementations return:
  {
    "clinical_term":  str,        human-readable symptom name
    "symptom_id":     str,        primary HP ID
    "symptom_ids":    list[str],  HP IDs (single-element list for now)
    "score":          float,      cosine similarity [0, 1]
  }

When your friend's dedicated Qdrant service is ready, replace the
search_symptom() body — the rest of the system never changes.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np
from sentence_transformers import SentenceTransformer

if TYPE_CHECKING:
    from knowledge.neo4j_client import Neo4jClient

logger = logging.getLogger(__name__)

_SIMILARITY_THRESHOLD = 0.30
_MODEL_NAME           = "all-MiniLM-L6-v2"

# Path to the JSON fallback, relative to this file
_SYMPTOM_INDEX_JSON = (
    Path(__file__).resolve().parent.parent / "data" / "processed" / "symptom_index.json"
)


class QdrantClient:
    """
    Semantic symptom search with automatic Neo4j → JSON fallback.

    Corpus loading order:
      1. Neo4j   (preferred — full 19k symptom corpus with live data)
      2. symptom_index.json  (fallback — generated by 2_parse_ontologies.py,
                              no database required)

    The sentence-transformer model and embeddings are class-level so they are
    shared across all instances in the same process (saves ~80 MB RAM).
    """

    _model:      SentenceTransformer | None = None
    _embeddings: np.ndarray | None          = None

    def __init__(self, neo4j_client: Neo4jClient | None = None):
        self._neo4j  = neo4j_client
        self._corpus: list[tuple[str, str, str]] = []  # (text, clinical_term, hp_id)
        self._load_corpus()

    # ------------------------------------------------------------------ #
    #  Corpus loading                                                      #
    # ------------------------------------------------------------------ #

    def _load_corpus(self) -> None:
        """Try Neo4j first; fall back to symptom_index.json if unavailable."""
        if self._neo4j is not None:
            try:
                self._load_corpus_from_neo4j()
                if self._corpus:
                    return
                logger.warning(
                    "QdrantClient: Neo4j returned no symptom rows — "
                    "falling back to symptom_index.json"
                )
            except Exception as exc:
                logger.warning(
                    "QdrantClient: Neo4j unavailable (%s) — "
                    "falling back to symptom_index.json", exc,
                )

        self._load_corpus_from_json()

    def _load_corpus_from_neo4j(self) -> None:
        """Pull symptom names + synonyms from Neo4j (category='symptom' only)."""
        logger.info("QdrantClient: loading symptom corpus from Neo4j …")
        with self._neo4j._driver.session() as session:
            rows = session.run(
                """
                MATCH (s:Symptom)
                WHERE s.category = 'symptom'
                RETURN s.id AS id, s.name AS name, s.synonyms AS synonyms
                """
            ).data()
        self._build_corpus(rows)
        logger.info(
            "QdrantClient: Neo4j corpus ready — %d entries", len(self._corpus)
        )

    def _load_corpus_from_json(self) -> None:
        """
        Load corpus from data/processed/symptom_index.json.

        Generated by `uv run neo4j-setup/2_parse_ontologies.py` — requires
        only the raw .obo files, no database.

        symptom_index.json format:
          { "HP:0002875": { "name": "Exertional dyspnoea", "synonyms": [...] }, ... }
        """
        if not _SYMPTOM_INDEX_JSON.exists():
            logger.error(
                "QdrantClient: symptom_index.json not found at %s. "
                "Run:  uv run neo4j-setup/2_parse_ontologies.py",
                _SYMPTOM_INDEX_JSON,
            )
            return

        logger.info("QdrantClient: loading symptom corpus from %s …", _SYMPTOM_INDEX_JSON)
        index = json.loads(_SYMPTOM_INDEX_JSON.read_text(encoding="utf-8"))

        rows = [
            {
                "id":       hp_id,
                "name":     info.get("name", "") if isinstance(info, dict) else str(info),
                "synonyms": info.get("synonyms", []) if isinstance(info, dict) else [],
            }
            for hp_id, info in index.items()
        ]
        self._build_corpus(rows)
        logger.info(
            "QdrantClient: JSON corpus ready — %d entries from %d symptoms",
            len(self._corpus), len(rows),
        )

    def _build_corpus(self, rows: list[dict]) -> None:
        """
        Convert symptom rows into (text, clinical_term, hp_id) tuples,
        encode them with sentence-transformers, and store as class-level state.
        """
        corpus: list[tuple[str, str, str]] = []
        for row in rows:
            hp_id = row.get("id", "")
            name  = row.get("name") or ""
            syns  = row.get("synonyms") or []
            if not hp_id or not name:
                continue
            corpus.append((name, name, hp_id))
            for syn in syns:
                if syn and syn != name:
                    corpus.append((syn, name, hp_id))

        if not corpus:
            return

        texts = [entry[0] for entry in corpus]

        if QdrantClient._model is None:
            logger.info("QdrantClient: loading sentence-transformer model '%s' …", _MODEL_NAME)
            QdrantClient._model = SentenceTransformer(_MODEL_NAME)

        QdrantClient._embeddings = QdrantClient._model.encode(
            texts, normalize_embeddings=True, show_progress_bar=False, batch_size=256,
        )
        self._corpus = corpus

    # ------------------------------------------------------------------ #
    #  Public interface                                                    #
    # ------------------------------------------------------------------ #

    def search_symptom(self, user_text: str) -> dict:
        """
        Map free-text patient complaint to the best-matching HPO symptom term.

        Returns:
            clinical_term  — HPO name (e.g. "Exertional dyspnoea")
            symptom_id     — HP ID string (e.g. "HP:0002875")
            symptom_ids    — [symptom_id]  (list for future multi-match support)
            score          — cosine similarity [0, 1]

        Falls back to HP:0000001 (root) with score=0 when nothing matches or
        the corpus is empty.
        """
        _fallback = {
            "clinical_term": "Unknown symptom",
            "symptom_id":    "HP:0000001",
            "symptom_ids":   ["HP:0000001"],
            "score":         0.0,
        }

        if not self._corpus or QdrantClient._embeddings is None:
            logger.warning(
                "QdrantClient.search_symptom: corpus is empty — "
                "run 2_parse_ontologies.py or check Neo4j connection"
            )
            return _fallback

        query  = QdrantClient._model.encode([user_text], normalize_embeddings=True)[0]
        scores = QdrantClient._embeddings @ query

        best_idx   = int(np.argmax(scores))
        best_score = float(scores[best_idx])

        if best_score < _SIMILARITY_THRESHOLD:
            return {**_fallback, "score": best_score}

        _text, clinical_term, hp_id = self._corpus[best_idx]
        return {
            "clinical_term": clinical_term,
            "symptom_id":    hp_id,
            "symptom_ids":   [hp_id],
            "score":         best_score,
        }
